# Generated by Django 4.2.14 on 2024-08-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0013_rename_user_cuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
