# Generated by Django 4.2.14 on 2024-08-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0014_alter_cuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='is_dark_theme',
            field=models.BooleanField(default=False),
        ),
    ]
