# Generated by Django 4.2.14 on 2024-08-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0015_cuser_is_dark_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='is_dark_theme',
        ),
        migrations.AlterField(
            model_name='cuser',
            name='userbg',
            field=models.CharField(blank=True, choices=[('true', 'TRUE'), ('false', 'FALSE')], default='false', max_length=30),
        ),
    ]
