# Generated by Django 4.2.14 on 2024-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0016_remove_cuser_is_dark_theme_alter_cuser_userbg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='is_dark_theme',
            field=models.CharField(blank=True, choices=[('true', 'TRUE'), ('false', 'FALSE')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='userbg',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('stars', 'Stars')], default='default', max_length=30),
        ),
    ]
