# Generated by Django 4.2.14 on 2024-08-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0017_cuser_is_dark_theme_alter_cuser_userbg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='is_dark_theme',
            field=models.CharField(choices=[('true', 'TRUE'), ('false', 'FALSE')], default='false', max_length=30),
        ),
    ]
