# Generated by Django 4.2.14 on 2024-09-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0021_alter_cuser_is_dark_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportname', models.CharField(max_length=30, verbose_name='Alert')),
                ('reportdescription', models.TextField(verbose_name='Description')),
                ('dronetarget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logins_and_alerts.drone')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logins_and_alerts.cuser')),
            ],
        ),
    ]
