# Generated by Django 4.2.14 on 2024-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0022_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='timeofalert',
            field=models.DateTimeField(default='2024-09-01 12:00', verbose_name='Date + Time of the alert'),
        ),
        migrations.AddField(
            model_name='report',
            name='timeofreport',
            field=models.DateTimeField(default='2024-09-01 12:00', verbose_name='Date + Time of the report'),
        ),
    ]
