# Generated by Django 4.2.14 on 2024-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0023_alert_timeofalert_report_timeofreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alertdescription',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timeofalert',
            field=models.DateTimeField(default='2024-09-01 12:00:00', verbose_name='Date + Time of the alert'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportdescription',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportname',
            field=models.CharField(max_length=30, verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='timeofreport',
            field=models.DateTimeField(default='2024-09-01 12:00:00', verbose_name='Date + Time of the report'),
        ),
    ]
