# Generated by Django 4.2.14 on 2024-09-02 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0024_alter_alert_alertdescription_alter_alert_timeofalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timeofalert',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 0), verbose_name='Date + Time of the alert'),
        ),
        migrations.AlterField(
            model_name='report',
            name='timeofreport',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 0), verbose_name='Date + Time of the report'),
        ),
    ]
