# Generated by Django 4.2.14 on 2024-09-02 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0025_alter_alert_timeofalert_alter_report_timeofreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='lastconnectiondate',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 12, 0), verbose_name='Last Connection Date'),
        ),
    ]
