# Generated by Django 4.2.14 on 2024-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0026_drone_lastconnectiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='userbg',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('alert', 'alert'), ('warning', 'warning'), ('info', 'info')], default='default', max_length=10),
        ),
    ]
