# Generated by Django 4.2.14 on 2024-09-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0027_alert_userbg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='userbg',
            new_name='type',
        ),
    ]
